apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-v1
  namespace: default
  labels:
    app: echoserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: echoserver
        version: v1
    spec:
      containers:
        - name: echoserver
          image: gigi0907/proxy-app
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
