apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: default
  labels:
    app: echoserver
    service: echoserver
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32080
      targetPort: 8080
      name: "http"
  selector:
    app: echoserver